#!/usr/bin/python
from __future__ import print_function

from std_msgs.msg import Header
import dlib
import roslib
roslib.load_manifest('unibas_face_distance_calculator')
import sys
import rospy
import cv2
import numpy as np
import message_filters
from std_msgs.msg import String
from sensor_msgs.msg import Image, CameraInfo
from cv_bridge import CvBridge, CvBridgeError
import math
from trajectory_msgs.msg import JointTrajectory
from trajectory_msgs.msg import JointTrajectoryPoint
import time
import moveit_msgs.msg
import moveit_commander

print("====== Starting tutorial setup")
moveit_commander.roscpp_initialize(sys.argv)
rospy.init_node('move_group_python_interface_tutorial',anonymous=True)
robot = moveit_commander.RobotCommander()
scene = moveit_commander.PlanningSceneInterface()
group = moveit_commander.MoveGroupCommander("manipulator")
display_trajectory_publisher = rospy.Publisher('move_group/display_planned_path',moveit_msgs.msg.DisplayTrajectory)
print ("====== Waiting for RVIZ ...")
rospy.sleep(10)
print ("====== Starting tutorial")
print ("====== Robot Groups:")
print (robot.get_group_names())
print ("====== Printing robot state")
print (robot.get_current_state())
print ("=============")
